// AUTO-GENERATED — Fırat Üniversitesi birim listesi (bildirim topic eşlemesi).
// Kaynak: firat.edu.tr birim dizini. Topic'ler BİZİM kendi Firebase projemizde (elazigapp) tanımlıdır.
// Toplam 342 birim. Yeniden üretmek için scratchpad/build_units.py.

export type FiratUnitCategory =
  | 'fakulte'
  | 'bolum'
  | 'enstitu'
  | 'yuksekokul'
  | 'myo'
  | 'daire'
  | 'idari'
  | 'koordinatorluk'
  | 'merkez'
  | 'topluluk'
  | 'diger';

export interface FiratUnit {
  id: number;
  name: string;
  nameEn?: string;
  sub: string;
  topic: string;
  url: string;
  category: FiratUnitCategory;
}

export const FIRAT_UNIT_CATEGORY_LABELS: Record<FiratUnitCategory, string> = {
  fakulte: "Fakülteler",
  bolum: "Bölümler / Anabilim Dalları",
  enstitu: "Enstitüler",
  yuksekokul: "Yüksekokullar",
  myo: "Meslek Yüksekokulları",
  daire: "Daire Başkanlıkları",
  idari: "İdari Birimler",
  koordinatorluk: "Koordinatörlükler",
  merkez: "Araştırma Merkezleri",
  topluluk: "Öğrenci Toplulukları",
  diger: "Diğer / Etkinlik",
};

export const FIRAT_UNITS: FiratUnit[] = [
  { id: 38, name: "Diş Hekimliği Fakültesi", nameEn: "FACULTY OF DENTISTRY", sub: "disf", topic: "firat_disf", url: "https://disf.firat.edu.tr", category: "fakulte" },
  { id: 201, name: "ECZACILIK FAKÜLTESİ", nameEn: "FACULTY OF PHARMACY", sub: "eczacilikf", topic: "firat_eczacilikf", url: "https://eczacilikf.firat.edu.tr", category: "fakulte" },
  { id: 12, name: "EĞİTİM FAKÜLTESİ", nameEn: "FACULTY OF EDUCATION", sub: "egitimf", topic: "firat_egitimf", url: "https://egitimf.firat.edu.tr", category: "fakulte" },
  { id: 13, name: "FEN FAKÜLTESİ", nameEn: "FACULTY OF SCIENCES", sub: "fenf", topic: "firat_fenf", url: "https://fenf.firat.edu.tr", category: "fakulte" },
  { id: 15, name: "İKTİSADİ VE İDARİ BİLİMLER FAKÜLTESİ", nameEn: "FACULTY OF ECONOMICS AND ADMINISTRATIVE SCIENCES", sub: "iibf", topic: "firat_iibf", url: "https://iibf.firat.edu.tr", category: "fakulte" },
  { id: 16, name: "İLAHİYAT FAKÜLTESİ", nameEn: "FACULTY OF THEOLOGY", sub: "ilahiyatf", topic: "firat_ilahiyatf", url: "https://ilahiyatf.firat.edu.tr", category: "fakulte" },
  { id: 17, name: "İLETİŞİM FAKÜLTESİ", nameEn: "FACULTY OF COMMUNICATION", sub: "iletisimf", topic: "firat_iletisimf", url: "https://iletisimf.firat.edu.tr", category: "fakulte" },
  { id: 18, name: "İnsan ve Toplum Bilimleri Fakültesi", nameEn: "Faculty of Humanities and Social Sciences", sub: "isbf", topic: "firat_isbf", url: "https://isbf.firat.edu.tr", category: "fakulte" },
  { id: 19, name: "Mimarlık Fakültesi", nameEn: "Faculty of Architecture", sub: "mimarlikf", topic: "firat_mimarlikf", url: "https://mimarlikf.firat.edu.tr", category: "fakulte" },
  { id: 9, name: "MÜHENDİSLİK FAKÜLTESİ", nameEn: "FACULTY OF ENGINEERING", sub: "muhendislikf", topic: "firat_muhendislikf", url: "https://muhendislikf.firat.edu.tr", category: "fakulte" },
  { id: 20, name: "SAĞLIK BİLİMLERİ FAKÜLTESİ", nameEn: "FACULTY OF HEALTH SCIENCES", sub: "saglikf", topic: "firat_saglikf", url: "https://saglikf.firat.edu.tr", category: "fakulte" },
  { id: 7, name: "SPOR BİLİMLERİ FAKÜLTESİ", nameEn: "FACULTY OF SPORTS SCIENCES", sub: "sporbilimlerif", topic: "firat_sporbilimlerif", url: "https://sporbilimlerif.firat.edu.tr", category: "fakulte" },
  { id: 21, name: "SU ÜRÜNLERİ FAKÜLTESİ", nameEn: "FACULTY OF FISHERIES", sub: "suuf", topic: "firat_suuf", url: "https://suuf.firat.edu.tr", category: "fakulte" },
  { id: 221, name: "Teknik Eğitim Fakültesi", nameEn: "Faculty of Technical Education", sub: "tef", topic: "firat_tef", url: "https://tef.firat.edu.tr", category: "fakulte" },
  { id: 10, name: "TEKNOLOJİ FAKÜLTESİ", nameEn: "FACULTY OF TECHNOLOGY", sub: "teknolojif", topic: "firat_teknolojif", url: "https://teknolojif.firat.edu.tr", category: "fakulte" },
  { id: 22, name: "TIP FAKÜLTESİ", nameEn: "FACULTY OF MEDICINE", sub: "tip", topic: "firat_tip", url: "https://tip.firat.edu.tr", category: "fakulte" },
  { id: 23, name: "VETERİNER FAKÜLTESİ", nameEn: "Faculty of Veterinary Science", sub: "veterinerf", topic: "firat_veterinerf", url: "https://veterinerf.firat.edu.tr", category: "fakulte" },
  { id: 50, name: "Adli Bilişim Mühendisliği", nameEn: "Digital Forensics Engineering", sub: "abmtf", topic: "firat_abmtf", url: "https://abmtf.firat.edu.tr", category: "bolum" },
  { id: 456, name: "Afet Bölgesinde Yer Alan Okullarda Gerçekleştirilecek Algı Yönetim Uygulamaları ile Öğretmenlerin Duygusal Bağlılık Düzeyleri Arasındaki İlişkinin İncelenmesi", nameEn: "Afet Bölgesinde Yer Alan Okullarda Gerçekleştirilecek Algı Yönetim Uygulamaları ile Öğretmenlerin Duygusal Bağlılık Düzeyleri Arasındaki İlişkinin İncelenmesi", sub: "aysis1001", topic: "firat_aysis1001", url: "https://aysis1001.firat.edu.tr", category: "bolum" },
  { id: 212, name: "Afet ve Kriz Yönetimi Anabilim Dalı", nameEn: "Afet ve Kriz Yönetimi Anabilim Dalı", sub: "akyabd", topic: "firat_akyabd", url: "https://akyabd.firat.edu.tr", category: "bolum" },
  { id: 71, name: "Aktüerya Bölümü", nameEn: "Department of Actuarial", sub: "aktuerya", topic: "firat_aktuerya", url: "https://aktuerya.firat.edu.tr", category: "bolum" },
  { id: 234, name: "Alman Dili ve Edebiyatı", nameEn: "German Language and Literature", sub: "alman", topic: "firat_alman", url: "https://alman.firat.edu.tr", category: "bolum" },
  { id: 481, name: "Anestezi Programı", nameEn: "Anestezi Programı", sub: "ansshmyo", topic: "firat_ansshmyo", url: "https://ansshmyo.firat.edu.tr", category: "bolum" },
  { id: 121, name: "Antrenörlük Eğitimi Bölümü", nameEn: "Department of Coaching Education", sub: "aeb", topic: "firat_aeb", url: "https://aeb.firat.edu.tr", category: "bolum" },
  { id: 85, name: "Arkeoloji Bölümü", nameEn: "Department of Archeology", sub: "arkeoloji", topic: "firat_arkeoloji", url: "https://arkeoloji.firat.edu.tr", category: "bolum" },
  { id: 542, name: "Aşçılık Programı", sub: "ascilik", topic: "firat_ascilik", url: "https://ascilik.firat.edu.tr", category: "bolum" },
  { id: 168, name: "Batı Dilleri ve Edebiyatları Bölümü", nameEn: "Department of Western Languages ​​and Literatures", sub: "bdeb", topic: "firat_bdeb", url: "https://bdeb.firat.edu.tr", category: "bolum" },
  { id: 122, name: "Beden Eğitimi ve Spor Öğretmenliği Bölümü", nameEn: "Department of Physical Education and Sports Teaching", sub: "beso", topic: "firat_beso", url: "https://beso.firat.edu.tr", category: "bolum" },
  { id: 60, name: "Beslenme ve Diyetetik Bölümü", nameEn: "Department of Nutrition and Dietetics", sub: "bd", topic: "firat_bd", url: "https://bd.firat.edu.tr", category: "bolum" },
  { id: 46, name: "Bilgisayar Mühendisliği", nameEn: "Computer Engineering", sub: "bilgisayarmf", topic: "firat_bilgisayarmf", url: "https://bilgisayarmf.firat.edu.tr", category: "bolum" },
  { id: 497, name: "Bilgisayar Teknolojileri Bölümü", nameEn: "Bilgisayar Teknolojileri Bölümü", sub: "bilgisayarkrcmyo", topic: "firat_bilgisayarkrcmyo", url: "https://bilgisayarkrcmyo.firat.edu.tr", category: "bolum" },
  { id: 98, name: "Bilgisayar ve Öğretim Teknolojileri Eğitimi Bölümü", nameEn: "Department of Computer Education and Instructional Technologies", sub: "bote", topic: "firat_bote", url: "https://bote.firat.edu.tr", category: "bolum" },
  { id: 43, name: "Biyoloji Programı ve Moleküler Biyoloji ve Genetik Programı", nameEn: "Biology Program and Molecular Biology and Genetics Program", sub: "biyoloji", topic: "firat_biyoloji", url: "https://biyoloji.firat.edu.tr", category: "bolum" },
  { id: 238, name: "Biyoteknoloji Anabilim Dalı", sub: "biyotek", topic: "firat_biyotek", url: "https://biyotek.firat.edu.tr", category: "bolum" },
  { id: 55, name: "Coğrafya Bölümü", nameEn: "Department of Geography", sub: "cb", topic: "firat_cb", url: "https://cb.firat.edu.tr", category: "bolum" },
  { id: 520, name: "Dış Ticaret Bölümü", sub: "disticaret", topic: "firat_disticaret", url: "https://disticaret.firat.edu.tr", category: "bolum" },
  { id: 61, name: "Ebelik Bölümü", nameEn: "Department of Midwifery", sub: "ebe", topic: "firat_ebe", url: "https://ebe.firat.edu.tr", category: "bolum" },
  { id: 128, name: "Ekobilişim Ana Bilim Dalı", nameEn: "Ecoinformatics Department", sub: "ekobilisimabd", topic: "firat_ekobilisimabd", url: "https://ekobilisimabd.firat.edu.tr", category: "bolum" },
  { id: 30, name: "Elektrik Elektronik Mühendisliği", nameEn: "Electrical Electronics Engineering", sub: "eemtf", topic: "firat_eemtf", url: "https://eemtf.firat.edu.tr", category: "bolum" },
  { id: 91, name: "Elektrik Elektronik Mühendisliği", nameEn: "Electrical Electronics Engineering", sub: "eemmf", topic: "firat_eemmf", url: "https://eemmf.firat.edu.tr", category: "bolum" },
  { id: 86, name: "Endüstri Ürünleri Tasarımı Bölümü", nameEn: "Department of Industrial Design", sub: "endustrimimarlik", topic: "firat_endustrimimarlik", url: "https://endustrimimarlik.firat.edu.tr", category: "bolum" },
  { id: 95, name: "Enerji Sistemleri Mühendisliği", nameEn: "Energy Systems Engineering", sub: "entf", topic: "firat_entf", url: "https://entf.firat.edu.tr", category: "bolum" },
  { id: 106, name: "Enformatik Bölümü", nameEn: "Department of Informatics", sub: "eb", topic: "firat_eb", url: "https://eb.firat.edu.tr", category: "bolum" },
  { id: 99, name: "Eğitim Bilimleri Bölümü", nameEn: "Department of Educational Sciences", sub: "ebb", topic: "firat_ebb", url: "https://ebb.firat.edu.tr", category: "bolum" },
  { id: 154, name: "Eğitim Programları ve Öğretim Anabilim Dalı", nameEn: "Department of Curriculum and Instruction", sub: "epoabd", topic: "firat_epoabd", url: "https://epoabd.firat.edu.tr", category: "bolum" },
  { id: 110, name: "Eğitim Yönetimi Ana Bilim Dalı", nameEn: "Department of Educational Administration", sub: "eyabd", topic: "firat_eyabd", url: "https://eyabd.firat.edu.tr", category: "bolum" },
  { id: 113, name: "Eğitimde Ölçme ve Değerlendirme Anabilim Dalı", nameEn: "Department of Measurement and Evoluation in Education", sub: "eod", topic: "firat_eod", url: "https://eod.firat.edu.tr", category: "bolum" },
  { id: 176, name: "Farabi Değişim Programı", nameEn: "Farabi Exchange Program", sub: "farabi", topic: "firat_farabi", url: "https://farabi.firat.edu.tr", category: "bolum" },
  { id: 312, name: "Felsefe ve Din Bilimleri Bölümü", nameEn: "Felsefe ve Din Bilimleri Bölümü", sub: "fdb", topic: "firat_fdb", url: "https://fdb.firat.edu.tr", category: "bolum" },
  { id: 111, name: "Fen Bilimleri Eğitimi Ana Bilim Dalı", nameEn: "Department of Science Education", sub: "fbeabd", topic: "firat_fbeabd", url: "https://fbeabd.firat.edu.tr", category: "bolum" },
  { id: 45, name: "Fizik Bölümü", nameEn: "Department of Physics", sub: "fizik", topic: "firat_fizik", url: "https://fizik.firat.edu.tr", category: "bolum" },
  { id: 482, name: "Fizyoterapi Programı", nameEn: "Fizyoterapi Programı", sub: "fztshmyo", topic: "firat_fztshmyo", url: "https://fztshmyo.firat.edu.tr", category: "bolum" },
  { id: 236, name: "Fransız Dili ve Edebiyatı", nameEn: "French Language and Literature", sub: "fransiz", topic: "firat_fransiz", url: "https://fransiz.firat.edu.tr", category: "bolum" },
  { id: 82, name: "Gazetecilik Bölümü", nameEn: "Department of Journalism", sub: "gazetecilik", topic: "firat_gazetecilik", url: "https://gazetecilik.firat.edu.tr", category: "bolum" },
  { id: 210, name: "Girişimcilik ve Yenilik Yönetimi Anabilim Dalı", nameEn: "Girişimcilik ve Yenilik Yönetimi Anabilim Dalı", sub: "gyysosyal", topic: "firat_gyysosyal", url: "https://gyysosyal.firat.edu.tr", category: "bolum" },
  { id: 100, name: "Güzel Sanatlar Eğitimi Bölümü Resim-İş Öğretmenliği Bölümü", nameEn: "Department of Fine Arts Education Department of Painting Crafts Education", sub: "gseb", topic: "firat_gseb", url: "https://gseb.firat.edu.tr", category: "bolum" },
  { id: 499, name: "Gıda İşleme Bölümü", nameEn: "Gıda İşleme Bölümü", sub: "gidakrcmyo", topic: "firat_gidakrcmyo", url: "https://gidakrcmyo.firat.edu.tr", category: "bolum" },
  { id: 63, name: "Hava Trafik Kontrolü Bölümü", nameEn: "Department of Air Traffic Control", sub: "htkb", topic: "firat_htkb", url: "https://htkb.firat.edu.tr", category: "bolum" },
  { id: 62, name: "Havacılık Elektrik ve Elektroniği Bölümü", nameEn: "Department of Aviation Electrical and Electronics", sub: "heeb", topic: "firat_heeb", url: "https://heeb.firat.edu.tr", category: "bolum" },
  { id: 97, name: "Hemşirelik Bölümü", nameEn: "Department of Nursing", sub: "hemsirelik", topic: "firat_hemsirelik", url: "https://hemsirelik.firat.edu.tr", category: "bolum" },
  { id: 75, name: "İktisat Bölümü", nameEn: "Department of Economics", sub: "iktisat", topic: "firat_iktisat", url: "https://iktisat.firat.edu.tr", category: "bolum" },
  { id: 101, name: "İlköğretim Bölümü", nameEn: "Department of Primary Education", sub: "iob", topic: "firat_iob", url: "https://iob.firat.edu.tr", category: "bolum" },
  { id: 102, name: "İlköğretim Matematik Öğretmenliği", nameEn: "Elementary Mathematics Teaching", sub: "imo", topic: "firat_imo", url: "https://imo.firat.edu.tr", category: "bolum" },
  { id: 235, name: "İngiliz Dili ve Edebiyatı", nameEn: "English Language and Literature", sub: "ingiliz", topic: "firat_ingiliz", url: "https://ingiliz.firat.edu.tr", category: "bolum" },
  { id: 109, name: "İngilizce Mütercim-Tercümanlık Bölümü", nameEn: "Department of English Translation and Interpretation", sub: "imt", topic: "firat_imt", url: "https://imt.firat.edu.tr", category: "bolum" },
  { id: 501, name: "İnşaat Bölümü", nameEn: "İnşaat Bölümü", sub: "insaatkrcmyo", topic: "firat_insaatkrcmyo", url: "https://insaatkrcmyo.firat.edu.tr", category: "bolum" },
  { id: 48, name: "İnşaat Mühendisliği", nameEn: "Civil Engineering", sub: "insaatmf", topic: "firat_insaatmf", url: "https://insaatmf.firat.edu.tr", category: "bolum" },
  { id: 51, name: "İnşaat Mühendisliği", nameEn: "Civil Engineering", sub: "insaattf", topic: "firat_insaattf", url: "https://insaattf.firat.edu.tr", category: "bolum" },
  { id: 313, name: "İslam Tarihi ve Sanatları Bölümü", nameEn: "İslam Tarihi ve Sanatları Bölümü", sub: "itsb", topic: "firat_itsb", url: "https://itsb.firat.edu.tr", category: "bolum" },
  { id: 44, name: "İstatistik Bölümü", nameEn: "Department of Statistics", sub: "istatistik", topic: "firat_istatistik", url: "https://istatistik.firat.edu.tr", category: "bolum" },
  { id: 87, name: "İç Mimarlık Bölümü", nameEn: "Department of Interior Architecture", sub: "icmimarlik", topic: "firat_icmimarlik", url: "https://icmimarlik.firat.edu.tr", category: "bolum" },
  { id: 76, name: "İş Sağlığı ve Güvenliği Ana Bilim Dalı", nameEn: "Department of Occupational Health and Safety", sub: "isg", topic: "firat_isg", url: "https://isg.firat.edu.tr", category: "bolum" },
  { id: 77, name: "İşletme Bölümü", nameEn: "Department of Business Administration", sub: "isletme", topic: "firat_isletme", url: "https://isletme.firat.edu.tr", category: "bolum" },
  { id: 92, name: "Jeodezi ve Fotogrametri (Geomatik) Mühendisliği", nameEn: "Geodesy and Photogrammetry (Geomatics) Engineering", sub: "geomatikmf", topic: "firat_geomatikmf", url: "https://geomatikmf.firat.edu.tr", category: "bolum" },
  { id: 93, name: "Jeoloji Mühendisliği", nameEn: "Geological Engineering", sub: "jeolojimf", topic: "firat_jeolojimf", url: "https://jeolojimf.firat.edu.tr", category: "bolum" },
  { id: 72, name: "Kimya Bölümü", nameEn: "Department of Chemistry", sub: "kimya", topic: "firat_kimya", url: "https://kimya.firat.edu.tr", category: "bolum" },
  { id: 49, name: "Kimya Mühendisliği", nameEn: "Chemical Engineering", sub: "kimyamf", topic: "firat_kimyamf", url: "https://kimyamf.firat.edu.tr", category: "bolum" },
  { id: 54, name: "Makina Mühendisliği", nameEn: "Mechanical Engineering", sub: "makinamf", topic: "firat_makinamf", url: "https://makinamf.firat.edu.tr", category: "bolum" },
  { id: 126, name: "Makina Mühendisliği", nameEn: "Mechanical Engineering", sub: "makinatf", topic: "firat_makinatf", url: "https://makinatf.firat.edu.tr", category: "bolum" },
  { id: 78, name: "Maliye Bölümü", nameEn: "Department of Finance", sub: "maliye", topic: "firat_maliye", url: "https://maliye.firat.edu.tr", category: "bolum" },
  { id: 73, name: "Matematik Bölümü", nameEn: "Department of Mathematics", sub: "matematik", topic: "firat_matematik", url: "https://matematik.firat.edu.tr", category: "bolum" },
  { id: 103, name: "Matematik ve Fen Bilimleri Eğitimi Bölümü", nameEn: "Department of Mathematics and Science Education", sub: "mfbeb", topic: "firat_mfbeb", url: "https://mfbeb.firat.edu.tr", category: "bolum" },
  { id: 52, name: "Mekatronik Mühendisliği", nameEn: "Mechatronic Engineering", sub: "mekatroniktf", topic: "firat_mekatroniktf", url: "https://mekatroniktf.firat.edu.tr", category: "bolum" },
  { id: 65, name: "Mekatronik Mühendisliği", nameEn: "Mechatronic Engineering", sub: "mekatronikmf", topic: "firat_mekatronikmf", url: "https://mekatronikmf.firat.edu.tr", category: "bolum" },
  { id: 53, name: "Metalurji ve Malzeme Mühendisliği", nameEn: "Metallurgy and Materials Engineering", sub: "mmtf", topic: "firat_mmtf", url: "https://mmtf.firat.edu.tr", category: "bolum" },
  { id: 94, name: "Metalurji ve Malzeme Mühendisliği", nameEn: "Metallurgy and Materials Engineering", sub: "mmmf", topic: "firat_mmmf", url: "https://mmmf.firat.edu.tr", category: "bolum" },
  { id: 175, name: "Mevlana Değişim Programı", nameEn: "Mevlana Student Exchange Programme", sub: "mevlana", topic: "firat_mevlana", url: "https://mevlana.firat.edu.tr", category: "bolum" },
  { id: 59, name: "Mimarlık Bölümü", nameEn: "Department of Architecture", sub: "mimarlik", topic: "firat_mimarlik", url: "https://mimarlik.firat.edu.tr", category: "bolum" },
  { id: 500, name: "Mimarlık ve Şehir Planlama Bölümü", nameEn: "Mimarlık ve Şehir Planlama Bölümü", sub: "mimarlikkrcmyo", topic: "firat_mimarlikkrcmyo", url: "https://mimarlikkrcmyo.firat.edu.tr", category: "bolum" },
  { id: 483, name: "Odyometri Programı", nameEn: "Odyometri Programı", sub: "odmshmyo", topic: "firat_odmshmyo", url: "https://odmshmyo.firat.edu.tr", category: "bolum" },
  { id: 104, name: "Okul Öncesi Eğitimi Ana Bilim Dalı", nameEn: "Department of Preschool Education", sub: "ooe", topic: "firat_ooe", url: "https://ooe.firat.edu.tr", category: "bolum" },
  { id: 455, name: "Orhun Değişim Programı", nameEn: "Orhun Exchange Program", sub: "orhun", topic: "firat_orhun", url: "https://orhun.firat.edu.tr", category: "bolum" },
  { id: 105, name: "Ortaöğretim Fen ve Matematik Alanları Bölümü", nameEn: "Department of Secondary Science and Mathematics", sub: "ofmb", topic: "firat_ofmb", url: "https://ofmb.firat.edu.tr", category: "bolum" },
  { id: 541, name: "Otel, Lokanta ve İkram Hizmetleri Bölümü", nameEn: "Otel, Lokanta ve İkram Hizmetleri Bölümü", sub: "turizmotel", topic: "firat_turizmotel", url: "https://turizmotel.firat.edu.tr", category: "bolum" },
  { id: 156, name: "Otomotiv Mühendisliği Bölümü", nameEn: "Department of Automotive Engineering", sub: "otomotivmf", topic: "firat_otomotivmf", url: "https://otomotivmf.firat.edu.tr", category: "bolum" },
  { id: 484, name: "Otopsi Yardımcılığı Programı", nameEn: "Otopsi Yardımcılığı Programı", sub: "otpshmyo", topic: "firat_otpshmyo", url: "https://otpshmyo.firat.edu.tr", category: "bolum" },
  { id: 155, name: "Psikolojik Danışma ve Rehberlik Anabilim Dalı", nameEn: "Department of Psychological Counseling and Guidance", sub: "pdrabd", topic: "firat_pdrabd", url: "https://pdrabd.firat.edu.tr", category: "bolum" },
  { id: 115, name: "Radyo-Televizyon ve Sinema Bölümü", nameEn: "Department of Radio-Television and Cinema", sub: "radyotv", topic: "firat_radyotv", url: "https://radyotv.firat.edu.tr", category: "bolum" },
  { id: 123, name: "Rekreasyon Bölümü", nameEn: "Department of Recreation", sub: "rek", topic: "firat_rek", url: "https://rek.firat.edu.tr", category: "bolum" },
  { id: 170, name: "Sanat Tarihi Bölümü", nameEn: "Department of Art History", sub: "sanattarihi", topic: "firat_sanattarihi", url: "https://sanattarihi.firat.edu.tr", category: "bolum" },
  { id: 80, name: "Siyaset Bilimi ve Kamu Yönetimi Bölümü", nameEn: "Political Science and Public Administration", sub: "sbkyb", topic: "firat_sbkyb", url: "https://sbkyb.firat.edu.tr", category: "bolum" },
  { id: 119, name: "Sosyal Bilgiler Eğitimi Ana Bilim Dalı", nameEn: "Department of Social Studies Education", sub: "sbeabd", topic: "firat_sbeabd", url: "https://sbeabd.firat.edu.tr", category: "bolum" },
  { id: 81, name: "Sosyal Hizmet Bölümü", nameEn: "Department of Social Work", sub: "shb", topic: "firat_shb", url: "https://shb.firat.edu.tr", category: "bolum" },
  { id: 56, name: "Sosyoloji Bölümü", nameEn: "Department of Sociology", sub: "sosyoloji", topic: "firat_sosyoloji", url: "https://sosyoloji.firat.edu.tr", category: "bolum" },
  { id: 124, name: "Spor Yöneticiliği Bölümü", nameEn: "Department of Sports Management", sub: "sy", topic: "firat_sy", url: "https://sy.firat.edu.tr", category: "bolum" },
  { id: 230, name: "Su Ürünleri Mühendisliği", nameEn: "Fisheries Engineering", sub: "sumf", topic: "firat_sumf", url: "https://sumf.firat.edu.tr", category: "bolum" },
  { id: 112, name: "Sınıf Eğitimi Anabilim Dalı", nameEn: "Department of Classroom Education", sub: "soabd", topic: "firat_soabd", url: "https://soabd.firat.edu.tr", category: "bolum" },
  { id: 57, name: "Tarih Bölümü", nameEn: "Department of History", sub: "tarih", topic: "firat_tarih", url: "https://tarih.firat.edu.tr", category: "bolum" },
  { id: 211, name: "Teknoloji ve Bilgi Yönetimi Anabilim Dalı", nameEn: "Teknoloji ve Bilgi Yönetimi Anabilim Dalı", sub: "tbysosyal", topic: "firat_tbysosyal", url: "https://tbysosyal.firat.edu.tr", category: "bolum" },
  { id: 116, name: "Temel Eğitim Bölümü", nameEn: "Department of Basic Education", sub: "teb", topic: "firat_teb", url: "https://teb.firat.edu.tr", category: "bolum" },
  { id: 311, name: "Temel İslam Bilimleri Bölümü", nameEn: "Temel İslam Bilimleri Bölümü", sub: "tib", topic: "firat_tib", url: "https://tib.firat.edu.tr", category: "bolum" },
  { id: 107, name: "Türk Dili Bölümü", nameEn: "Department of Turkish Language", sub: "turkdili", topic: "firat_turkdili", url: "https://turkdili.firat.edu.tr", category: "bolum" },
  { id: 58, name: "Türk Dili ve Edebiyatı Bölümü", nameEn: "Department of Turkish Language and Literature", sub: "turkdiliedb", topic: "firat_turkdiliedb", url: "https://turkdiliedb.firat.edu.tr", category: "bolum" },
  { id: 68, name: "Türkçe Eğitimi Ana Bilim Dalı", nameEn: "Department of Turkish Education", sub: "teabd", topic: "firat_teabd", url: "https://teabd.firat.edu.tr", category: "bolum" },
  { id: 117, name: "Türkçe Eğitimi Ana Bilim Dalı", nameEn: "Department of Turkish Education", sub: "teabdegitimf", topic: "firat_teabdegitimf", url: "https://teabdegitimf.firat.edu.tr", category: "bolum" },
  { id: 118, name: "Türkçe ve Sosyal Bilimler Eğitimi Bölümü", nameEn: "Department of Turkish and Social Sciences Education", sub: "tsbb", topic: "firat_tsbb", url: "https://tsbb.firat.edu.tr", category: "bolum" },
  { id: 485, name: "Tıbbi Dokümantasyon ve Sekreterlik Programı", nameEn: "Tıbbi Dokümantasyon ve Sekreterlik Programı", sub: "tdsshmyo", topic: "firat_tdsshmyo", url: "https://tdsshmyo.firat.edu.tr", category: "bolum" },
  { id: 486, name: "Tıbbi Görüntüleme Teknikleri Programı", nameEn: "Tıbbi Görüntüleme Teknikleri Programı", sub: "tgtshmyo", topic: "firat_tgtshmyo", url: "https://tgtshmyo.firat.edu.tr", category: "bolum" },
  { id: 64, name: "Uçak Bakım ve Onarım Bölümü", nameEn: "Department of Aircraf Maintenance and Repair", sub: "ubob", topic: "firat_ubob", url: "https://ubob.firat.edu.tr", category: "bolum" },
  { id: 70, name: "Yabancı Diller Eğitimi Bölümü", nameEn: "Department of Foreign Language Education", sub: "ydeb", topic: "firat_ydeb", url: "https://ydeb.firat.edu.tr", category: "bolum" },
  { id: 114, name: "Yabancı Diller Eğitimi Bölümü", nameEn: "Department of Foreign Language Education", sub: "ydebegitimf", topic: "firat_ydebegitimf", url: "https://ydebegitimf.firat.edu.tr", category: "bolum" },
  { id: 298, name: "Yapay Zeka ve Veri Mühendisliği", nameEn: "Artificial Intelligence and Data Engineering", sub: "yzvm", topic: "firat_yzvm", url: "https://yzvm.firat.edu.tr", category: "bolum" },
  { id: 5, name: "Yazılım Mühendisliği", nameEn: "Software Engineering", sub: "yazmf", topic: "firat_yazmf", url: "https://yazmf.firat.edu.tr", category: "bolum" },
  { id: 11, name: "Yazılım Mühendisliği", nameEn: "Software Engineering", sub: "yazilimtf", topic: "firat_yazilimtf", url: "https://yazilimtf.firat.edu.tr", category: "bolum" },
  { id: 129, name: "Yazılım Mühendisliği Uluslararası Ortak Lisans Programı", nameEn: "Software Engineering International Joint Degree Program", sub: "yazilimmuholp", topic: "firat_yazilimmuholp", url: "https://yazilimmuholp.firat.edu.tr", category: "bolum" },
  { id: 74, name: "Çalışma Ekonomisi ve Endüstri İlişkileri Bölümü", nameEn: "Depatment of Labor Economics and Industrial Relations", sub: "ceeib", topic: "firat_ceeib", url: "https://ceeib.firat.edu.tr", category: "bolum" },
  { id: 143, name: "Çağdaş Türk Lehçeleri ve Edebiyatları Bölümü", nameEn: "Department of Contemporary Turkish Dialects and Literatures", sub: "ctleb", topic: "firat_ctleb", url: "https://ctleb.firat.edu.tr", category: "bolum" },
  { id: 90, name: "Çevre Mühendisliği", nameEn: "Environmental Engineering", sub: "cevremf", topic: "firat_cevremf", url: "https://cevremf.firat.edu.tr", category: "bolum" },
  { id: 498, name: "Çocuk Bakımı ve Gençlik Hizmetleri Bölümü", nameEn: "Çocuk Bakımı ve Gençlik Hizmetleri Bölümü", sub: "cocukkrcmyo", topic: "firat_cocukkrcmyo", url: "https://cocukkrcmyo.firat.edu.tr", category: "bolum" },
  { id: 540, name: "Çocuk Gelişimi Programı", sub: "cglshmyo", topic: "firat_cglshmyo", url: "https://cglshmyo.firat.edu.tr", category: "bolum" },
  { id: 461, name: "Öğretim Teknolojileri Anabilim Dalı", nameEn: "Öğretim Teknolojileri Anabilim Dalı", sub: "oteabd", topic: "firat_oteabd", url: "https://oteabd.firat.edu.tr", category: "bolum" },
  { id: 89, name: "Şehir ve Bölge Planlama Bölümü", nameEn: "Department of City and Regional Planning", sub: "planlamamimarlik", topic: "firat_planlamamimarlik", url: "https://planlamamimarlik.firat.edu.tr", category: "bolum" },
  { id: 183, name: "Enstitüler Sayfası", nameEn: "Institutes Page", sub: "enstituler", topic: "firat_enstituler", url: "https://enstituler.firat.edu.tr", category: "enstitu" },
  { id: 40, name: "Eğitim Bilimleri Enstitüsü", nameEn: "Graduate Institute for Educational Sciences", sub: "egitim", topic: "firat_egitim", url: "https://egitim.firat.edu.tr", category: "enstitu" },
  { id: 29, name: "Fen Bilimleri Enstitüsü", nameEn: "Graduate School of Natural and Applied Sciences", sub: "fen", topic: "firat_fen", url: "https://fen.firat.edu.tr", category: "enstitu" },
  { id: 495, name: "Fen Bilimleri Enstitüsü", nameEn: "Graduate School of Natural and Applied Sciences", sub: "fbe", topic: "firat_fbe", url: "https://fbe.firat.edu.tr", category: "enstitu" },
  { id: 39, name: "Sağlık Bilimleri Enstitüsü", nameEn: "Graduate Institute for Health Sciences", sub: "saglik", topic: "firat_saglik", url: "https://saglik.firat.edu.tr", category: "enstitu" },
  { id: 36, name: "Sosyal Bilimler Enstitüsü", nameEn: "Graduate Institute for Social Sciences", sub: "sosyal", topic: "firat_sosyal", url: "https://sosyal.firat.edu.tr", category: "enstitu" },
  { id: 488, name: "Yazılım ve Bilişim Araştırma Enstitüsü", nameEn: "Yazılım ve Bilişim Araştırma Enstitüsü", sub: "yazbil", topic: "firat_yazbil", url: "https://yazbil.firat.edu.tr", category: "enstitu" },
  { id: 24, name: "DEVLET KONSERVATUVARI", nameEn: "STATE CONSERVATORY", sub: "kyo", topic: "firat_kyo", url: "https://kyo.firat.edu.tr", category: "yuksekokul" },
  { id: 25, name: "SİVİL HAVACILIK YÜKSEKOKULU", nameEn: "SCHOOL OF CIVIL AVIATION", sub: "sivilhavacilik", topic: "firat_sivilhavacilik", url: "https://sivilhavacilik.firat.edu.tr", category: "yuksekokul" },
  { id: 26, name: "YABANCI DİLLER YÜKSEKOKULU", nameEn: "SCHOOL OF FOREIGN LANGUAGES", sub: "yabancidiller", topic: "firat_yabancidiller", url: "https://yabancidiller.firat.edu.tr", category: "yuksekokul" },
  { id: 31, name: "Baskil Meslek Yüksek Okulu", nameEn: "Baskil Vocational School", sub: "baskil", topic: "firat_baskil", url: "https://baskil.firat.edu.tr", category: "myo" },
  { id: 34, name: "Elazığ Organize Sanayi Bölgesi Meslek Yüksekokulu", nameEn: "Vocational School of Elazığ Organized Industrial Zone", sub: "sanayi", topic: "firat_sanayi", url: "https://sanayi.firat.edu.tr", category: "myo" },
  { id: 28, name: "KARAKOÇAN MESLEK YÜKSEK OKULU", nameEn: "Karakoçan Vocational School", sub: "karakocan", topic: "firat_karakocan", url: "https://karakocan.firat.edu.tr", category: "myo" },
  { id: 27, name: "KEBAN MESLEK YÜKSEKOKULU", nameEn: "Keban Vocational School", sub: "keban", topic: "firat_keban", url: "https://keban.firat.edu.tr", category: "myo" },
  { id: 32, name: "Kovancılar Meslek Yüksek Okulu", nameEn: "Kovancılar Vocational School", sub: "kovancilar", topic: "firat_kovancilar", url: "https://kovancilar.firat.edu.tr", category: "myo" },
  { id: 41, name: "Sağlık Hizmetleri Meslek Yüksekokulu", nameEn: "Vocational School of Health Services", sub: "saglikmyo", topic: "firat_saglikmyo", url: "https://saglikmyo.firat.edu.tr", category: "myo" },
  { id: 35, name: "Sivrice Meslek Yüksek Okulu", nameEn: "Sivrice Vocational School", sub: "sivrice", topic: "firat_sivrice", url: "https://sivrice.firat.edu.tr", category: "myo" },
  { id: 42, name: "Sosyal Bilimler Meslek Yüksek Okulu", nameEn: "Vocational School of Social Sciences", sub: "sosyalmyo", topic: "firat_sosyalmyo", url: "https://sosyalmyo.firat.edu.tr", category: "myo" },
  { id: 37, name: "Teknik Bilimler Meslek Yüksekokulu", nameEn: "Vocational School of Technical Sciences", sub: "teknik", topic: "firat_teknik", url: "https://teknik.firat.edu.tr", category: "myo" },
  { id: 145, name: "Bilgi İşlem Daire Başkanlığı", nameEn: "Department of Information Technologies", sub: "bilgiislemdb", topic: "firat_bilgiislemdb", url: "https://bilgiislemdb.firat.edu.tr", category: "daire" },
  { id: 144, name: "Genel Sekreterlik", nameEn: "Secretary General", sub: "gsekreterlik", topic: "firat_gsekreterlik", url: "https://gsekreterlik.firat.edu.tr", category: "daire" },
  { id: 147, name: "İdari ve Mali İşler Daire Başkanlığı", nameEn: "Department of Administrative and Financial Affairs", sub: "imdb", topic: "firat_imdb", url: "https://imdb.firat.edu.tr", category: "daire" },
  { id: 163, name: "İç Denetim Birimi Başkanlığı", nameEn: "Internel Audit Unit", sub: "icdenetim", topic: "firat_icdenetim", url: "https://icdenetim.firat.edu.tr", category: "daire" },
  { id: 148, name: "Kütüphane ve Dokümantasyon Daire Başkanlığı", nameEn: "Department of Library and Documentation", sub: "kutuphanedb", topic: "firat_kutuphanedb", url: "https://kutuphanedb.firat.edu.tr", category: "daire" },
  { id: 150, name: "Personel Daire Başkanlığı", nameEn: "Office of Staff Affairs", sub: "personeldb", topic: "firat_personeldb", url: "https://personeldb.firat.edu.tr", category: "daire" },
  { id: 146, name: "Sağlık Kültür ve Spor Daire Başkanlığı", nameEn: "Department of Health, Culture and Sports", sub: "sksdab", topic: "firat_sksdab", url: "https://sksdab.firat.edu.tr", category: "daire" },
  { id: 151, name: "Strateji Geliştirme Daire Başkanlığı", nameEn: "Department of Strategy Development", sub: "stratejidb", topic: "firat_stratejidb", url: "https://stratejidb.firat.edu.tr", category: "daire" },
  { id: 152, name: "Yapı İşleri Daire Başkanlığı", nameEn: "Department of Construction Works", sub: "yapidb", topic: "firat_yapidb", url: "https://yapidb.firat.edu.tr", category: "daire" },
  { id: 450, name: "Özel Kalem Müdürlüğü", nameEn: "Office Of The Rector", sub: "ozelkalem", topic: "firat_ozelkalem", url: "https://ozelkalem.firat.edu.tr", category: "daire" },
  { id: 149, name: "Öğrenci İşleri Daire Başkanlığı", nameEn: "Registrar and Student Affairs Office", sub: "ogrencidb", topic: "firat_ogrencidb", url: "https://ogrencidb.firat.edu.tr", category: "daire" },
  { id: 157, name: "Basın Yayın Müdürlüğü", nameEn: "Department of Press and Publication", sub: "basin", topic: "firat_basin", url: "https://basin.firat.edu.tr", category: "idari" },
  { id: 363, name: "FIRAT ÜNİVERSİTESİ DÖNER SERMAYE İŞLETME MÜDÜRLÜĞÜ", nameEn: "FIRAT ÜNİVERSİTESİ DÖNER SERMAYE İŞLETME MÜDÜRLÜĞÜ", sub: "donersermaye", topic: "firat_donersermaye", url: "https://donersermaye.firat.edu.tr", category: "idari" },
  { id: 136, name: "Fırat Üniversitesi Ağız ve Diş Sağlığı Hastanesi", nameEn: "Elazig Firat University Oral and Dental Health Center", sub: "dismer", topic: "firat_dismer", url: "https://dismer.firat.edu.tr", category: "idari" },
  { id: 158, name: "Güvenlik Şube Müdürlüğü", nameEn: "Security Branch Directorate", sub: "guvenlik", topic: "firat_guvenlik", url: "https://guvenlik.firat.edu.tr", category: "idari" },
  { id: 167, name: "Hayvan Hastanesi", nameEn: "Animal Hospital", sub: "hayvanhastanesi", topic: "firat_hayvanhastanesi", url: "https://hayvanhastanesi.firat.edu.tr", category: "idari" },
  { id: 180, name: "Karakoçan Yurt", nameEn: "Karakocan Dorm", sub: "karakocanyurt", topic: "firat_karakocanyurt", url: "https://karakocanyurt.firat.edu.tr", category: "idari" },
  { id: 178, name: "Sosyal Tesisler İktisadi İşletmesi", nameEn: "Social Facilities", sub: "sosyaltesisler", topic: "firat_sosyaltesisler", url: "https://sosyaltesisler.firat.edu.tr", category: "idari" },
  { id: 433, name: "Bilimsel Dergi Koordinatörlüğü", nameEn: "Scientific Journal Coordination", sub: "bdk", topic: "firat_bdk", url: "https://bdk.firat.edu.tr", category: "koordinatorluk" },
  { id: 532, name: "Bilimsel Dergiler Koordinatörlüğü", nameEn: "Bilimsel Dergiler Koordinatörlüğü", sub: "dergiler", topic: "firat_dergiler", url: "https://dergiler.firat.edu.tr", category: "koordinatorluk" },
  { id: 3, name: "DİJİTAL DÖNÜŞÜM ve YAZILIM OFİSİ KOORDİNATÖRLÜĞÜ", nameEn: "DIGITAL TRANSFORMATION AND SOFTWARE OFFICE", sub: "ddyo", topic: "firat_ddyo", url: "https://ddyo.firat.edu.tr", category: "koordinatorluk" },
  { id: 160, name: "Erasmus+ Kurum Koordinatörlüğü", nameEn: "Erasmus+ Institutional Coordination", sub: "disiliskilerkoord", topic: "firat_disiliskilerkoord", url: "https://disiliskilerkoord.firat.edu.tr", category: "koordinatorluk" },
  { id: 480, name: "Erasmus+ Kurum Koordinatörlüğü", nameEn: "Erasmus+ Institutional Coordination Office", sub: "erasmus", topic: "firat_erasmus", url: "https://erasmus.firat.edu.tr", category: "koordinatorluk" },
  { id: 162, name: "F.Ü. ÖSYM Koordinatörlüğü", nameEn: "F.U. OSYM Coordinatorship", sub: "osymkoord", topic: "firat_osymkoord", url: "https://osymkoord.firat.edu.tr", category: "koordinatorluk" },
  { id: 161, name: "F.Ü. ÖYP Koordinatörlüğü", nameEn: "F.U. ÖYP Coordinatorship", sub: "oypkoord", topic: "firat_oypkoord", url: "https://oypkoord.firat.edu.tr", category: "koordinatorluk" },
  { id: 231, name: "Fırat Üniversitesi Araştırma Koordinatörlüğü", nameEn: "Firat University Research Coordination", sub: "ardek", topic: "firat_ardek", url: "https://ardek.firat.edu.tr", category: "koordinatorluk" },
  { id: 491, name: "Fırat Üniversitesi Bilim İletişimi Koordinatörlüğü", nameEn: "Fırat Üniversitesi Bilim İletişimi Koordinatörlüğü", sub: "bilimiletisim", topic: "firat_bilimiletisim", url: "https://bilimiletisim.firat.edu.tr", category: "koordinatorluk" },
  { id: 164, name: "Fırat Üniversitesi Kalite Koordinatörlüğü", nameEn: "Firat University Quality Coordination Office", sub: "kalitekoord", topic: "firat_kalitekoord", url: "https://kalitekoord.firat.edu.tr", category: "koordinatorluk" },
  { id: 159, name: "Hukuk Müşavirliği Koordinatörlüğü", nameEn: "Legal Consultancy Office", sub: "hukukkoord", topic: "firat_hukukkoord", url: "https://hukukkoord.firat.edu.tr", category: "koordinatorluk" },
  { id: 458, name: "İş Sağlığı ve Güvenliği Koordinatörlüğü", nameEn: "İş Sağlığı ve Güvenliği Koordinatörlüğü", sub: "fuisg", topic: "firat_fuisg", url: "https://fuisg.firat.edu.tr", category: "koordinatorluk" },
  { id: 8, name: "KURUMSAL İLETİŞİM KOORDİNATÖRLÜĞÜ", nameEn: "Office of Corporate Communications", sub: "kikoord", topic: "firat_kikoord", url: "https://kikoord.firat.edu.tr", category: "koordinatorluk" },
  { id: 477, name: "Sosyal Seçmeli Dersler Koordinatörlüğü", nameEn: "Sosyal Seçmeli Dersler Koordinatörlüğü", sub: "ssdkoord", topic: "firat_ssdkoord", url: "https://ssdkoord.firat.edu.tr", category: "koordinatorluk" },
  { id: 478, name: "Toplumsal Katkı Koordinatörlüğü", nameEn: "Toplumsal Katkı Koordinatörlüğü", sub: "toplumsalkatki", topic: "firat_toplumsalkatki", url: "https://toplumsalkatki.firat.edu.tr", category: "koordinatorluk" },
  { id: 224, name: "ÖĞRENCİ KOORDİNATÖRLÜĞÜ", nameEn: "STUDENT COORDINATORSHIP", sub: "ogrencidekanligi", topic: "firat_ogrencidekanligi", url: "https://ogrencidekanligi.firat.edu.tr", category: "koordinatorluk" },
  { id: 134, name: "Akademik Yazma Uygulama ve Araştırma Merkezi", nameEn: "ACADEMIC WRITING APPLICATION AND RESEARCH CENTER", sub: "akademikyazmamer", topic: "firat_akademikyazmamer", url: "https://akademikyazmamer.firat.edu.tr", category: "merkez" },
  { id: 135, name: "Bilgisayar Bilimleri Araştırma ve Uygulama Merkezi", nameEn: "Center for Research in Computer Sciences", sub: "baum", topic: "firat_baum", url: "https://baum.firat.edu.tr", category: "merkez" },
  { id: 454, name: "Bitki Doku Kültürü Laboratuvarı", nameEn: "Plant Tissue Culture Laboratory", sub: "bdkl", topic: "firat_bdkl", url: "https://bdkl.firat.edu.tr", category: "merkez" },
  { id: 132, name: "Deneysel Araştırma Merkezi", nameEn: "Experimental Research Center", sub: "deneyselarastirmamer", topic: "firat_deneyselarastirmamer", url: "https://deneyselarastirmamer.firat.edu.tr", category: "merkez" },
  { id: 138, name: "Engelliler Araştırma ve Uygulama Merkezi", nameEn: "Disabled Research and Application Center", sub: "engelsizmer", topic: "firat_engelsizmer", url: "https://engelsizmer.firat.edu.tr", category: "merkez" },
  { id: 137, name: "Engelsiz Yaşam Uygulama ve Araştırma Merkezi", nameEn: "Fırat University Center for Disability Research and Support", sub: "engellimer", topic: "firat_engellimer", url: "https://engellimer.firat.edu.tr", category: "merkez" },
  { id: 131, name: "Fırat Üniversitesi Kadın ve Aile Çalışmaları Uygulama ve Araştırma Merkezi", nameEn: "F.U. Women's Studies Application and Research Center", sub: "kadincalismalarimer", topic: "firat_kadincalismalarimer", url: "https://kadincalismalarimer.firat.edu.tr", category: "merkez" },
  { id: 239, name: "Fırat Üniversitesi Sanayi İşbirliği Merkezi", sub: "fusim", topic: "firat_fusim", url: "https://fusim.firat.edu.tr", category: "merkez" },
  { id: 133, name: "Fırat Üniversitesi Uzaktan Eğitim Merkezi", nameEn: "Firat University Distance Education Center", sub: "u", topic: "firat_u", url: "https://u.firat.edu.tr", category: "merkez" },
  { id: 226, name: "Fırat Üniversitesi Uzaktan Eğitim Merkezi", nameEn: "Firat University Distance Education Center", sub: "fuzem", topic: "firat_fuzem", url: "https://fuzem.firat.edu.tr", category: "merkez" },
  { id: 186, name: "Harput Uygulama ve Araştırma Merkezi", nameEn: "Fırat University Center for Harput Heritage and Research", sub: "harputmer", topic: "firat_harputmer", url: "https://harputmer.firat.edu.tr", category: "merkez" },
  { id: 200, name: "İKLİM DEĞİŞİKLİĞİ, ÇEVRE VE YEŞİL KALKINMA UYGULAMA VE ARAŞTIRMA MERKEZİ", nameEn: "CLIMATE CHANGE, ENVIRONMENT AND GREEN DEVELOPMENT IMPLEMENTATION AND RESEARCH CENTER", sub: "iklimcevremer", topic: "firat_iklimcevremer", url: "https://iklimcevremer.firat.edu.tr", category: "merkez" },
  { id: 141, name: "Kariyer Planlama Uygulama ve Araştırma Merkezi", nameEn: "Career Planning Application and Research Center", sub: "kariyermer", topic: "firat_kariyermer", url: "https://kariyermer.firat.edu.tr", category: "merkez" },
  { id: 460, name: "MERLAB", nameEn: "MERLAB", sub: "merkezilab", topic: "firat_merkezilab", url: "https://merkezilab.firat.edu.tr", category: "merkez" },
  { id: 434, name: "NÖRO PAZARLAMA VE PAZARLAMA ARAŞTIRMA MERKEZİ", nameEn: "NEURO MARKETING AND MARKETING RESEARCH CENTER", sub: "noro", topic: "firat_noro", url: "https://noro.firat.edu.tr", category: "merkez" },
  { id: 165, name: "Proje Koordinasyon ve Danışmanlık Merkezi", nameEn: "Project Coordination and Consultancy Office Coordinator", sub: "projekoord", topic: "firat_projekoord", url: "https://projekoord.firat.edu.tr", category: "merkez" },
  { id: 203, name: "Robotik ve Yapay Zeka Laboratuvarı (RAI)", nameEn: "Robotics and Artificial Intelligence Laboratory (RAI)", sub: "rai", topic: "firat_rai", url: "https://rai.firat.edu.tr", category: "merkez" },
  { id: 140, name: "Tarım ve Hayvancılık Araştırma ve Uygulama Merkezi", nameEn: "Fırat University Center for Agriculture and Livestock Research", sub: "tarimhayvancilikmer", topic: "firat_tarimhayvancilikmer", url: "https://tarimhayvancilikmer.firat.edu.tr", category: "merkez" },
  { id: 139, name: "Türkçe Öğretimi Uygulama ve Araştırma Merkezi", nameEn: "Turkish Teaching Application and Research Center", sub: "turkceogretimimer", topic: "firat_turkceogretimimer", url: "https://turkceogretimimer.firat.edu.tr", category: "merkez" },
  { id: 487, name: "Tıbbi Laboratuvar Teknikleri Programı", nameEn: "Tıbbi Laboratuvar Teknikleri Programı", sub: "tltshmyo", topic: "firat_tltshmyo", url: "https://tltshmyo.firat.edu.tr", category: "merkez" },
  { id: 120, name: "Yapı ve Beton Uygulama ve Araştırma Merkezi (YABEM)", nameEn: "F.U Center for Earthquake-Resilient Construction and Concrete Technologies", sub: "yabem", topic: "firat_yabem", url: "https://yabem.firat.edu.tr", category: "merkez" },
  { id: 185, name: "Yerbilimleri Uygulama ve Araştırma Merkezi", nameEn: "Geosciences Research and Application Center", sub: "yerbilimleri", topic: "firat_yerbilimleri", url: "https://yerbilimleri.firat.edu.tr", category: "merkez" },
  { id: 490, name: "Çevre Sorunları Uygulama ve Araştırma Merkez Müdürlüğü", nameEn: "Çevre Sorunları Uygulama ve Araştırma Merkez Müdürlüğü", sub: "fucsuam", topic: "firat_fucsuam", url: "https://fucsuam.firat.edu.tr", category: "merkez" },
  { id: 266, name: "ACM Fırat Öğrenci Topluluğu", sub: "acm", topic: "firat_acm", url: "https://acm.firat.edu.tr", category: "topluluk" },
  { id: 504, name: "Adli Bilişim Topluluğu", nameEn: "Adli Bilişim Topluluğu", sub: "adlibilisimtoplulugu", topic: "firat_adlibilisimtoplulugu", url: "https://adlibilisimtoplulugu.firat.edu.tr", category: "topluluk" },
  { id: 259, name: "Adli Bilişim Öğrenci Topluluğu", sub: "adlibilisim", topic: "firat_adlibilisim", url: "https://adlibilisim.firat.edu.tr", category: "topluluk" },
  { id: 275, name: "Akademik Düşünce Eğitim Medeniyet Öğrenci Topluluğu", sub: "adem", topic: "firat_adem", url: "https://adem.firat.edu.tr", category: "topluluk" },
  { id: 417, name: "Analitik Düşünce Öğrenci Topluluğu", nameEn: "Analitik Düşünce Öğrenci Topluluğu", sub: "adt", topic: "firat_adt", url: "https://adt.firat.edu.tr", category: "topluluk" },
  { id: 420, name: "Anatomi Müzesi Geliştirme Topluluğu", nameEn: "Anatomi Müzesi Geliştirme Topluluğu", sub: "anatomimuzesi", topic: "firat_anatomimuzesi", url: "https://anatomimuzesi.firat.edu.tr", category: "topluluk" },
  { id: 505, name: "Bilim ve fen topluluğu", nameEn: "Bilim ve fen topluluğu", sub: "bilimvefen", topic: "firat_bilimvefen", url: "https://bilimvefen.firat.edu.tr", category: "topluluk" },
  { id: 418, name: "Bilim ve Kimya Öğrenci Topluluğu", nameEn: "Bilim ve Kimya Öğrenci Topluluğu", sub: "bilkim", topic: "firat_bilkim", url: "https://bilkim.firat.edu.tr", category: "topluluk" },
  { id: 359, name: "Bilişim ve Eğitim Öğrenci Topluluğu", nameEn: "Bilişim ve Eğitim Öğrenci Topluluğu", sub: "fubet", topic: "firat_fubet", url: "https://fubet.firat.edu.tr", category: "topluluk" },
  { id: 413, name: "Bir Dünya Oyuncak Öğrenci Topluluğu", nameEn: "Bir Dünya Oyuncak Öğrenci Topluluğu", sub: "bdo", topic: "firat_bdo", url: "https://bdo.firat.edu.tr", category: "topluluk" },
  { id: 515, name: "Biyobilim topluluğu", nameEn: "Biyobilim topluluğu", sub: "biyobilim", topic: "firat_biyobilim", url: "https://biyobilim.firat.edu.tr", category: "topluluk" },
  { id: 256, name: "Biyoloji / Moleküler Biyoloji ve Genetik Öğrenci Topluluğu", sub: "genetik", topic: "firat_genetik", url: "https://genetik.firat.edu.tr", category: "topluluk" },
  { id: 424, name: "Bulut Bilişim ve Büyük Veri Öğrenci Topluluğu", nameEn: "Bulut Bilişim ve Büyük Veri Öğrenci Topluluğu", sub: "bbvot", topic: "firat_bbvot", url: "https://bbvot.firat.edu.tr", category: "topluluk" },
  { id: 419, name: "Damla Öğrenci Topluluğu", nameEn: "Damla Öğrenci Topluluğu", sub: "damla", topic: "firat_damla", url: "https://damla.firat.edu.tr", category: "topluluk" },
  { id: 353, name: "Dâru'l-Hadis Öğrenci Topluluğu", nameEn: "Dâru'l-Hadis Öğrenci Topluluğu", sub: "darulhadis", topic: "firat_darulhadis", url: "https://darulhadis.firat.edu.tr", category: "topluluk" },
  { id: 427, name: "Düşlerden Gülüşlere Öğrenci Topluluğu", nameEn: "Düşlerden Gülüşlere Öğrenci Topluluğu", sub: "duslerdenguluslere", topic: "firat_duslerdenguluslere", url: "https://duslerdenguluslere.firat.edu.tr", category: "topluluk" },
  { id: 421, name: "Düşünce Akademisi Öğrenci Topluluğu", nameEn: "Düşünce Akademisi Öğrenci Topluluğu", sub: "dusunceakd", topic: "firat_dusunceakd", url: "https://dusunceakd.firat.edu.tr", category: "topluluk" },
  { id: 426, name: "Ebelik Öğrenci Topluluğu", nameEn: "Ebelik Öğrenci Topluluğu", sub: "ebelikot", topic: "firat_ebelikot", url: "https://ebelikot.firat.edu.tr", category: "topluluk" },
  { id: 356, name: "Eczacılık Öğrenci Topluluğu", nameEn: "Eczacılık Öğrenci Topluluğu", sub: "fupsa", topic: "firat_fupsa", url: "https://fupsa.firat.edu.tr", category: "topluluk" },
  { id: 251, name: "Erasmus Öğrenci Topluluğu", sub: "erasmustoplulugu", topic: "firat_erasmustoplulugu", url: "https://erasmustoplulugu.firat.edu.tr", category: "topluluk" },
  { id: 534, name: "FARMAGENÇ ÖĞRENCİ TOPLULUĞU", nameEn: "FARMAGENÇ ÖĞRENCİ TOPLULUĞU", sub: "farmagenc", topic: "firat_farmagenc", url: "https://farmagenc.firat.edu.tr", category: "topluluk" },
  { id: 431, name: "FIRAT ÜNİVERSİTESİ ÖĞRENCİ TOPLULUKLARI", nameEn: "FIRAT ÜNİVERSİTESİ ÖĞRENCİ TOPLULUKLARI", sub: "ogrencitopluluklari", topic: "firat_ogrencitopluluklari", url: "https://ogrencitopluluklari.firat.edu.tr", category: "topluluk" },
  { id: 510, name: "Firatunivet öğrenci topluluğu", nameEn: "Firatunivet öğrenci topluluğu", sub: "firatunivet", topic: "firat_firatunivet", url: "https://firatunivet.firat.edu.tr", category: "topluluk" },
  { id: 514, name: "Fizik ve Bilim Topluluğu", nameEn: "Fizik ve Bilim Topluluğu", sub: "fufizbit", topic: "firat_fufizbit", url: "https://fufizbit.firat.edu.tr", category: "topluluk" },
  { id: 249, name: "Fizyoterapi ve Rehabilitasyon Öğrenci Topluluğu", sub: "ftrtoplulugu", topic: "firat_ftrtoplulugu", url: "https://ftrtoplulugu.firat.edu.tr", category: "topluluk" },
  { id: 428, name: "Fotoğrafçılık Öğrenci Topluluğu", nameEn: "Fotoğrafçılık Öğrenci Topluluğu", sub: "fotografcilikot", topic: "firat_fotografcilikot", url: "https://fotografcilikot.firat.edu.tr", category: "topluluk" },
  { id: 355, name: "Fırat Blockchain Öğrenci Topluluğu", nameEn: "Fırat Blockchain Öğrenci Topluluğu", sub: "blockchain", topic: "firat_blockchain", url: "https://blockchain.firat.edu.tr", category: "topluluk" },
  { id: 516, name: "Fırat Edebiyat Topluluğu", nameEn: "Fırat Edebiyat Topluluğu", sub: "edebiyatogrencitoplulugu", topic: "firat_edebiyatogrencitoplulugu", url: "https://edebiyatogrencitoplulugu.firat.edu.tr", category: "topluluk" },
  { id: 349, name: "Fırat Sinefi Öğrenci Topluluğu", nameEn: "Fırat Sinefi Öğrenci Topluluğu", sub: "sinefi", topic: "firat_sinefi", url: "https://sinefi.firat.edu.tr", category: "topluluk" },
  { id: 263, name: "Fırat Üniversitesi Dans Öğrenci Topluluğu", sub: "fudans", topic: "firat_fudans", url: "https://fudans.firat.edu.tr", category: "topluluk" },
  { id: 245, name: "Fırat Üniversitesi Elektro Teknoloji Öğrenci Topluluğu", sub: "elektroteknoloji", topic: "firat_elektroteknoloji", url: "https://elektroteknoloji.firat.edu.tr", category: "topluluk" },
  { id: 507, name: "Fırat Üniversitesi Gastronomi Topluluğu", nameEn: "Fırat Üniversitesi Gastronomi Topluluğu", sub: "fuga", topic: "firat_fuga", url: "https://fuga.firat.edu.tr", category: "topluluk" },
  { id: 262, name: "Fırat Üniversitesi Havacılık ve Uzay Teknolojileri Öğrenci Topluluğu", sub: "havacilikuzay", topic: "firat_havacilikuzay", url: "https://havacilikuzay.firat.edu.tr", category: "topluluk" },
  { id: 512, name: "Fırat Üniversitesi Münazara Topluluğu", nameEn: "Fırat Üniversitesi Münazara Topluluğu", sub: "munazara", topic: "firat_munazara", url: "https://munazara.firat.edu.tr", category: "topluluk" },
  { id: 351, name: "Fırat Üniversitesi Satranç Öğrenci Topluluğu", nameEn: "Fırat Üniversitesi Satranç Öğrenci Topluluğu", sub: "satranc", topic: "firat_satranc", url: "https://satranc.firat.edu.tr", category: "topluluk" },
  { id: 253, name: "Fırat Üniversitesi Siber Güvenlik Öğrecni Topluluğu", sub: "siberguvenlik", topic: "firat_siberguvenlik", url: "https://siberguvenlik.firat.edu.tr", category: "topluluk" },
  { id: 247, name: "Fırat Üniversitesi Teknoloji Ar-Ge ve Girişimcilik Öğrenci Topluluğu", sub: "futag", topic: "firat_futag", url: "https://futag.firat.edu.tr", category: "topluluk" },
  { id: 246, name: "Fırat Üniversitesi Teknoloji Öğrenci Topluluğu", sub: "futek", topic: "firat_futek", url: "https://futek.firat.edu.tr", category: "topluluk" },
  { id: 255, name: "Fırat Üniversitesi Tiyatro Öğrenci Topluluğu", sub: "tiyatro", topic: "firat_tiyatro", url: "https://tiyatro.firat.edu.tr", category: "topluluk" },
  { id: 261, name: "Fırat Üniversitesi Veteriner Fakültesi Öğrenci Topluluğu", sub: "fuvet", topic: "firat_fuvet", url: "https://fuvet.firat.edu.tr", category: "topluluk" },
  { id: 422, name: "Gastronomi Topluluğu", nameEn: "Gastronomi Topluluğu", sub: "gastronomiot", topic: "firat_gastronomiot", url: "https://gastronomiot.firat.edu.tr", category: "topluluk" },
  { id: 358, name: "Genç Bakış Topluluğu", nameEn: "Genç Bakış Topluluğu", sub: "geba", topic: "firat_geba", url: "https://geba.firat.edu.tr", category: "topluluk" },
  { id: 252, name: "Genç Girişimciler Öğrenci Topluluğu", sub: "gencgirisimciler", topic: "firat_gencgirisimciler", url: "https://gencgirisimciler.firat.edu.tr", category: "topluluk" },
  { id: 357, name: "Genç Yeşilay", nameEn: "Genç Yeşilay", sub: "yesilay", topic: "firat_yesilay", url: "https://yesilay.firat.edu.tr", category: "topluluk" },
  { id: 279, name: "Gezi ve Turizm Öğrenci Topluluğu", sub: "gezitur", topic: "firat_gezitur", url: "https://gezitur.firat.edu.tr", category: "topluluk" },
  { id: 453, name: "Görsel İletişim Atölyesi Öğrenci Topluluğu", nameEn: "Visual Communication Workshop Student Community", sub: "gia", topic: "firat_gia", url: "https://gia.firat.edu.tr", category: "topluluk" },
  { id: 270, name: "Havacılık Öğrenci Topluluğu", sub: "fuhak", topic: "firat_fuhak", url: "https://fuhak.firat.edu.tr", category: "topluluk" },
  { id: 429, name: "Hemşirelik Öğrenci Topluluğu", nameEn: "Hemşirelik Öğrenci Topluluğu", sub: "hemsirelikot", topic: "firat_hemsirelikot", url: "https://hemsirelikot.firat.edu.tr", category: "topluluk" },
  { id: 272, name: "Huawei Geliştirici Öğrenciler Öğrenci Topluluğu", sub: "hsd", topic: "firat_hsd", url: "https://hsd.firat.edu.tr", category: "topluluk" },
  { id: 264, name: "Institute of Electrical and Electronics Engineers Öğrenci Topluluğu", sub: "ieee", topic: "firat_ieee", url: "https://ieee.firat.edu.tr", category: "topluluk" },
  { id: 265, name: "İngiliz Dili ve Edebiyatı Öğrenci Topluluğu", sub: "ideall", topic: "firat_ideall", url: "https://ideall.firat.edu.tr", category: "topluluk" },
  { id: 273, name: "Kalite Öğrenci Topluluğu", sub: "fukat", topic: "firat_fukat", url: "https://fukat.firat.edu.tr", category: "topluluk" },
  { id: 258, name: "Kitap Severler Öğrenci Topluluğu", sub: "kst", topic: "firat_kst", url: "https://kst.firat.edu.tr", category: "topluluk" },
  { id: 257, name: "Makine Mühendisliği Öğrenci Topluluğu", sub: "fumm", topic: "firat_fumm", url: "https://fumm.firat.edu.tr", category: "topluluk" },
  { id: 414, name: "Matematik ve Teknoloji Öğrenci Topluluğu", nameEn: "Matematik ve Teknoloji Öğrenci Topluluğu", sub: "matek", topic: "firat_matek", url: "https://matek.firat.edu.tr", category: "topluluk" },
  { id: 415, name: "Mikro Mühendisler Öğrenci Topluluğu", nameEn: "Mikro Mühendisler Öğrenci Topluluğu", sub: "mikromuh", topic: "firat_mikromuh", url: "https://mikromuh.firat.edu.tr", category: "topluluk" },
  { id: 506, name: "Milli Kardeşlik Topluluğu", nameEn: "Milli Kardeşlik Topluluğu", sub: "millikardeslik", topic: "firat_millikardeslik", url: "https://millikardeslik.firat.edu.tr", category: "topluluk" },
  { id: 503, name: "Milli Türk Talebe Birliği Öğrenci Topluluğu", nameEn: "Milli Türk Talebe Birliği Öğrenci Topluluğu", sub: "firatmttb", topic: "firat_firatmttb", url: "https://firatmttb.firat.edu.tr", category: "topluluk" },
  { id: 425, name: "NEFHA Öğrenci Topluluğu", nameEn: "NEFHA Öğrenci Topluluğu", sub: "nefha", topic: "firat_nefha", url: "https://nefha.firat.edu.tr", category: "topluluk" },
  { id: 509, name: "Neşeli Adımlar Topluluğu", nameEn: "Neşeli Adımlar Topluluğu", sub: "neseliadimlar", topic: "firat_neseliadimlar", url: "https://neseliadimlar.firat.edu.tr", category: "topluluk" },
  { id: 248, name: "Rehber Öğrenci Topluluğu", sub: "rehberogrenci", topic: "firat_rehberogrenci", url: "https://rehberogrenci.firat.edu.tr", category: "topluluk" },
  { id: 277, name: "Saha Veteriner Hekimliği Öğrenci Topluluğu", sub: "sahavet", topic: "firat_sahavet", url: "https://sahavet.firat.edu.tr", category: "topluluk" },
  { id: 271, name: "Sosyal Ar-Ge Öğrenci Topluluğu", sub: "sosyalarge", topic: "firat_sosyalarge", url: "https://sosyalarge.firat.edu.tr", category: "topluluk" },
  { id: 274, name: "Sosyal Bilimlerde Teknoloji ve Araştırma Öğrenci Topluluğu", sub: "fustat", topic: "firat_fustat", url: "https://fustat.firat.edu.tr", category: "topluluk" },
  { id: 269, name: "Sosyal Hekimler Öğrenci Topluluğu", sub: "sosyalhekimler", topic: "firat_sosyalhekimler", url: "https://sosyalhekimler.firat.edu.tr", category: "topluluk" },
  { id: 250, name: "Sosyal Hizmet Etkileşim ve Farkındalık Öğrenci Topluluğu", sub: "shefk", topic: "firat_shefk", url: "https://shefk.firat.edu.tr", category: "topluluk" },
  { id: 423, name: "Spor Bilimleri Gönüllüleri Öğrenci Topluluğu", nameEn: "Spor Bilimleri Gönüllüleri Öğrenci Topluluğu", sub: "sbgot", topic: "firat_sbgot", url: "https://sbgot.firat.edu.tr", category: "topluluk" },
  { id: 254, name: "Sınıf Eğitimi Öğrenci Topluluğu", sub: "sinifegitimi", topic: "firat_sinifegitimi", url: "https://sinifegitimi.firat.edu.tr", category: "topluluk" },
  { id: 410, name: "Teknofest Öğrenci Topluluğu", nameEn: "Teknofest Öğrenci Topluluğu", sub: "teknofestfirat", topic: "firat_teknofestfirat", url: "https://teknofestfirat.firat.edu.tr", category: "topluluk" },
  { id: 352, name: "TURKMSIC-Fırat Öğrenci Topluluğu", nameEn: "TURKMSIC-Fırat Öğrenci Topluluğu", sub: "firattob", topic: "firat_firattob", url: "https://firattob.firat.edu.tr", category: "topluluk" },
  { id: 278, name: "Tıbbi Hizmetler ve Teknikerler Öğrenci Topluluğu", sub: "tht", topic: "firat_tht", url: "https://tht.firat.edu.tr", category: "topluluk" },
  { id: 268, name: "Uluslararası Doktorlar Birliği Öğrenci Topluluğu", sub: "aid", topic: "firat_aid", url: "https://aid.firat.edu.tr", category: "topluluk" },
  { id: 217, name: "Uluslararası Veteriner Öğrencileri Topluluğu (IVSA Elazığ)", nameEn: "International Veterinary Students Association", sub: "ivsa", topic: "firat_ivsa", url: "https://ivsa.firat.edu.tr", category: "topluluk" },
  { id: 513, name: "Uluslararası Öğrenci Topluluğu", nameEn: "Uluslararası Öğrenci Topluluğu", sub: "fuis", topic: "firat_fuis", url: "https://fuis.firat.edu.tr", category: "topluluk" },
  { id: 416, name: "Veri Bilimi ve İstatistik Öğrenci Topluluğu", nameEn: "Veri Bilimi ve İstatistik Öğrenci Topluluğu", sub: "vebist", topic: "firat_vebist", url: "https://vebist.firat.edu.tr", category: "topluluk" },
  { id: 276, name: "Veterinerlik Bilimsel Araştırma Yayın Öğrenci Topluluğu", sub: "vetbak", topic: "firat_vetbak", url: "https://vetbak.firat.edu.tr", category: "topluluk" },
  { id: 267, name: "Yabancı Dil Öğrenci Topluluğu", sub: "yabancidil", topic: "firat_yabancidil", url: "https://yabancidil.firat.edu.tr", category: "topluluk" },
  { id: 319, name: "Yapay Zeka, Görüntü İşleme ve İnovasyon Öğrenci Topluluğu", nameEn: "Artificial Intelligence, Image Processing and Innovation Student Community", sub: "yzgii", topic: "firat_yzgii", url: "https://yzgii.firat.edu.tr", category: "topluluk" },
  { id: 354, name: "Yapı - Tasarım Öğrenci Topluluğu", nameEn: "Yapı - Tasarım Öğrenci Topluluğu", sub: "ytt", topic: "firat_ytt", url: "https://ytt.firat.edu.tr", category: "topluluk" },
  { id: 412, name: "Yedi Kıta Öğrenci Topluluğu", nameEn: "Yedi Kıta Öğrenci Topluluğu", sub: "yedikita", topic: "firat_yedikita", url: "https://yedikita.firat.edu.tr", category: "topluluk" },
  { id: 166, name: "Asfalt Günleri Çalıştayı", nameEn: "Asphalt Days Workshop", sub: "asfaltgunleri", topic: "firat_asfaltgunleri", url: "https://asfaltgunleri.firat.edu.tr", category: "diger" },
  { id: 47, name: "Biyomühendislik", nameEn: "Bioengineering", sub: "bmmf", topic: "firat_bmmf", url: "https://bmmf.firat.edu.tr", category: "diger" },
  { id: 296, name: "BİDEB 2237-A Akademide Dijital Araçlar ve Akademik Gelişim Sezon 2", nameEn: "BİDEB 2237 - A - Digital Tools in Academy And Academical Career Development Season 2", sub: "2237akademikgelisim", topic: "firat_2237akademikgelisim", url: "https://2237akademikgelisim.firat.edu.tr", category: "diger" },
  { id: 361, name: "ChemBridge Araştırma Grubu", nameEn: "ChemBridge Araştırma Grubu", sub: "chembridgeresearchgroup", topic: "firat_chembridgeresearchgroup", url: "https://chembridgeresearchgroup.firat.edu.tr", category: "diger" },
  { id: 225, name: "Code-23 FIRAT YAZILIM ATÖLYESİ", nameEn: "CODE-23 FIRAT SOFTWARE WORKSHOP", sub: "code23", topic: "firat_code23", url: "https://code23.firat.edu.tr", category: "diger" },
  { id: 127, name: "COVID 19", nameEn: "COVID 19", sub: "covid", topic: "firat_covid", url: "https://covid.firat.edu.tr", category: "diger" },
  { id: 196, name: "Değer Proje", nameEn: "Değer Proje", sub: "degerproje", topic: "firat_degerproje", url: "https://degerproje.firat.edu.tr", category: "diger" },
  { id: 202, name: "DOĞU ANADOLU FAY ZONU'NUN ERKENEK VE SÜRGÜ SEGMENTLERİNİN DEPREM DAVRANIŞI", nameEn: "DOĞU ANADOLU FAY ZONU'NUN ERKENEK VE SÜRGÜ SEGMENTLERİNİN DEPREM DAVRANIŞI", sub: "dafzsurguerkenek", topic: "firat_dafzsurguerkenek", url: "https://dafzsurguerkenek.firat.edu.tr", category: "diger" },
  { id: 222, name: "EBYS YARDIM WEB SAYFASI", nameEn: "EBYS HELP WEBSITE", sub: "ebysyardim", topic: "firat_ebysyardim", url: "https://ebysyardim.firat.edu.tr", category: "diger" },
  { id: 194, name: "EMAT4005", nameEn: "EMAT4005", sub: "emat4005proje", topic: "firat_emat4005proje", url: "https://emat4005proje.firat.edu.tr", category: "diger" },
  { id: 314, name: "Erken Çocuklukta Ahlak ve Değerler Eğitimi", nameEn: "Erken Çocuklukta Ahlak ve Değerler Eğitimi", sub: "ecad", topic: "firat_ecad", url: "https://ecad.firat.edu.tr", category: "diger" },
  { id: 177, name: "Etik Kurullar", nameEn: "Ethics committees", sub: "etikkurullar", topic: "firat_etikkurullar", url: "https://etikkurullar.firat.edu.tr", category: "diger" },
  { id: 233, name: "Eğitim Komisyonu", nameEn: "Education Commission", sub: "ekom", topic: "firat_ekom", url: "https://ekom.firat.edu.tr", category: "diger" },
  { id: 142, name: "F.Ü. Bilgi Edinme Birimi", nameEn: "F.U. Information Unit", sub: "bilgiedinme", topic: "firat_bilgiedinme", url: "https://bilgiedinme.firat.edu.tr", category: "diger" },
  { id: 281, name: "FEBİTEK", sub: "febitek", topic: "firat_febitek", url: "https://febitek.firat.edu.tr", category: "diger" },
  { id: 96, name: "Fizyoterapi ve Rehabilitasyon", nameEn: "Physical Threapy and Rehabilitation", sub: "ftr", topic: "firat_ftr", url: "https://ftr.firat.edu.tr", category: "diger" },
  { id: 536, name: "FUJİHES", nameEn: "FUJİHES", sub: "fujihes", topic: "firat_fujihes", url: "https://fujihes.firat.edu.tr", category: "diger" },
  { id: 502, name: "FUTURE", nameEn: "FUTURE", sub: "future", topic: "firat_future", url: "https://future.firat.edu.tr", category: "diger" },
  { id: 479, name: "Fırat Kısa Film Festivali", nameEn: "Fırat Kısa Film Festivali", sub: "festival", topic: "firat_festival", url: "https://festival.firat.edu.tr", category: "diger" },
  { id: 189, name: "Fırat TV", nameEn: "Fırat TV", sub: "tv", topic: "firat_tv", url: "https://tv.firat.edu.tr", category: "diger" },
  { id: 533, name: "Fırat University Journal of Software and Informatics Research Institute", nameEn: "Fırat University Journal of Software and Informatics Research Institute- FUJSIRI", sub: "fujsiri", topic: "firat_fujsiri", url: "https://fujsiri.firat.edu.tr", category: "diger" },
  { id: 511, name: "Fırat Üniversitesi Bulut Bilişim ve Büyük Veri (FUB3V)", nameEn: "Fırat Üniversitesi Bulut Bilişim ve Büyük Veri (FUB3V)", sub: "fub3v", topic: "firat_fub3v", url: "https://fub3v.firat.edu.tr", category: "diger" },
  { id: 260, name: "Google Developer Students Club Fırat University", sub: "gdsc", topic: "firat_gdsc", url: "https://gdsc.firat.edu.tr", category: "diger" },
  { id: 83, name: "Görsel İletişim Tasarımı", nameEn: "Visual Communication Design", sub: "gorseliletisim", topic: "firat_gorseliletisim", url: "https://gorseliletisim.firat.edu.tr", category: "diger" },
  { id: 84, name: "Halkla İlişkiler ve Tanıtım", nameEn: "Public Relations and Publicity", sub: "hitb", topic: "firat_hitb", url: "https://hitb.firat.edu.tr", category: "diger" },
  { id: 182, name: "Harput İç Kale Kazıları", nameEn: "Harput Inner Castle Excavations", sub: "harputickalekazilari", topic: "firat_harputickalekazilari", url: "https://harputickalekazilari.firat.edu.tr", category: "diger" },
  { id: 376, name: "Harput Klasik Hadis Meclisi", nameEn: "Harput Klasik Hadis Meclisi", sub: "harputklasikhadismeclisi", topic: "firat_harputklasikhadismeclisi", url: "https://harputklasikhadismeclisi.firat.edu.tr", category: "diger" },
  { id: 192, name: "Hemşirelik Eğitiminde Dönüşüm Sempozyumu", nameEn: "Symposium in Transformation of Nursing Education", sub: "hemegitimdonusum.etk", topic: "firat_hemegitimdonusum_etk", url: "https://hemegitimdonusum.etk.firat.edu.tr", category: "diger" },
  { id: 153, name: "İHA Pilotluk", nameEn: "UAV Piloting", sub: "ihakurs", topic: "firat_ihakurs", url: "https://ihakurs.firat.edu.tr", category: "diger" },
  { id: 190, name: "İSLAM VE MEDENİYET SEMPOZYUMU", nameEn: "Islam and Civilization Symposium", sub: "islamvemedeniyet", topic: "firat_islamvemedeniyet", url: "https://islamvemedeniyet.firat.edu.tr", category: "diger" },
  { id: 457, name: "İç Kontrol", nameEn: "İç Kontrol", sub: "ickontrol", topic: "firat_ickontrol", url: "https://ickontrol.firat.edu.tr", category: "diger" },
  { id: 195, name: "İçerik Tasarımı", nameEn: "İçerik Tasarımı", sub: "iceriktasarimi", topic: "firat_iceriktasarimi", url: "https://iceriktasarimi.firat.edu.tr", category: "diger" },
  { id: 216, name: "Karşılıklı Anlaşılabilirlik Yöntem ve Teknikleri", nameEn: "Mutual Understanding Methods and Techniques", sub: "kayt", topic: "firat_kayt", url: "https://kayt.firat.edu.tr", category: "diger" },
  { id: 191, name: "Kişisel Verilerin Korunması", nameEn: "Personal Data Protection", sub: "kvkk", topic: "firat_kvkk", url: "https://kvkk.firat.edu.tr", category: "diger" },
  { id: 213, name: "Mezuniyet 2022", nameEn: "Mezuniyet 2022", sub: "mezuniyet2022", topic: "firat_mezuniyet2022", url: "https://mezuniyet2022.firat.edu.tr", category: "diger" },
  { id: 198, name: "Nitel Araştırma", nameEn: "Nitel Araştırma", sub: "nitelarastirma", topic: "firat_nitelarastirma", url: "https://nitelarastirma.firat.edu.tr", category: "diger" },
  { id: 187, name: "Obezite Cerrahisi Bakımında Güncel Yaklaşımlar Sempozyumu", nameEn: "Current Approaches in Obesity Surgery Care Symposium", sub: "ocbhsemp", topic: "firat_ocbhsemp", url: "https://ocbhsemp.firat.edu.tr", category: "diger" },
  { id: 188, name: "Otomatik Kontrol Türk Milli Komitesi Ulusal Kongresi", nameEn: "Automatic Control Turkish National Committee National Congress", sub: "tok2022", topic: "firat_tok2022", url: "https://tok2022.firat.edu.tr", category: "diger" },
  { id: 227, name: "PEDAGOJİK FORMASYON EĞİTİMİ", nameEn: "PEDAGOGICAL FORMATION EDUCATION", sub: "pfe", topic: "firat_pfe", url: "https://pfe.firat.edu.tr", category: "diger" },
  { id: 88, name: "Peyzaj Mimarisi", nameEn: "Department of Landspace Architecture", sub: "peyzajmimarlik", topic: "firat_peyzajmimarlik", url: "https://peyzajmimarlik.firat.edu.tr", category: "diger" },
  { id: 174, name: "Salgın Danışma Komisyonu", nameEn: "Epidemic Advisory Commission", sub: "sdk", topic: "firat_sdk", url: "https://sdk.firat.edu.tr", category: "diger" },
  { id: 350, name: "Savunma Teknolojileri ve Nitelikli Mühendisler", nameEn: "Savunma Teknolojileri ve Nitelikli Mühendisler", sub: "stnm", topic: "firat_stnm", url: "https://stnm.firat.edu.tr", category: "diger" },
  { id: 79, name: "Sağlık Yönetimi", nameEn: "Healthcare Management", sub: "sagyon", topic: "firat_sagyon", url: "https://sagyon.firat.edu.tr", category: "diger" },
  { id: 496, name: "Sürdürülebilirlik", nameEn: "Sürdürülebilirlik", sub: "surdurulebilirlik", topic: "firat_surdurulebilirlik", url: "https://surdurulebilirlik.firat.edu.tr", category: "diger" },
  { id: 320, name: "UKOM", nameEn: "UKOM", sub: "ukom", topic: "firat_ukom", url: "https://ukom.firat.edu.tr", category: "diger" },
  { id: 193, name: "ULUSLARARASI ÖĞRENCİ OFİSİ", nameEn: "International Student Office", sub: "iso", topic: "firat_iso", url: "https://iso.firat.edu.tr", category: "diger" },
  { id: 181, name: "Uluslararası Öğrenci Sınavı", nameEn: "International Student Exam", sub: "uos", topic: "firat_uos", url: "https://uos.firat.edu.tr", category: "diger" },
  { id: 322, name: "Uzay, Savunma ve Bilişim Teknolojileri Dergisi", nameEn: "The Journal of Space, Defense and Information Technology", sub: "usbtjournal", topic: "firat_usbtjournal", url: "https://usbtjournal.firat.edu.tr", category: "diger" },
  { id: 508, name: "Vetakort", nameEn: "Vetakort", sub: "vetakort", topic: "firat_vetakort", url: "https://vetakort.firat.edu.tr", category: "diger" },
  { id: 214, name: "YAPAY ZEKA", nameEn: "ARTIFICIAL INTELLIGENCE", sub: "2237yapayzeka", topic: "firat_2237yapayzeka", url: "https://2237yapayzeka.firat.edu.tr", category: "diger" },
  { id: 184, name: "Yaz Okulu", nameEn: "Summer School", sub: "yazokuluyeni", topic: "firat_yazokuluyeni", url: "https://yazokuluyeni.firat.edu.tr", category: "diger" },
  { id: 125, name: "Yönetim Bilişim Sistemleri", nameEn: "Management Information Systems", sub: "yonbil", topic: "firat_yonbil", url: "https://yonbil.firat.edu.tr", category: "diger" },
  { id: 199, name: "Ölçek Geliştirme", nameEn: "Ölçek Geliştirme", sub: "olcekgelistirme", topic: "firat_olcekgelistirme", url: "https://olcekgelistirme.firat.edu.tr", category: "diger" },
  { id: 179, name: "Üniversite Evi", nameEn: "University Dining Hall", sub: "unievi", topic: "firat_unievi", url: "https://unievi.firat.edu.tr", category: "diger" },
];
